### ISSUE TITLE
user guide document 

### ISSUE THREAD

**Issue by lokyse** [paralin/go-dota2#21]
Any document to guide user how to use this library?

**Comment by brebernjak** [comment]
+1, please consider doing so as node-dota2 is now deprecated and this seems to be the most up to date client out there.

**Comment by paralin** [comment]
If someone wants to contribute one, I'll merge it.

**Comment by UnixCr3wR0x** [comment]
@paralin atleast at low level docs then we can try we actually cant use it

**Comment by paralin** [comment]
Basic overview:

 1. SetPlaying(true)
 2. Wait a moment (like 0.5 second)
 3. SayHello()
 4. Wait for the connection status event to indicate you have a gc session (IsReady() = true)
 5. Send SayHello every few seconds until you get a session
 6. Once you have IsReady() = true send CreateLobby.

I don't want to give too much detail as I'm not interested in being responsible for a flood of low-quality bots.

**Comment by AngelloFD** [comment]
Any update on this? Is anyone working on a documentation or at least have a way to start a project up with the library correctly?

**Comment by voltageeee** [comment]
> Any update on this? Is anyone working on a documentation or at least have a way to start a project up with the library correctly?

sorry to re-open this thread, but i guess some people will need help with this library from time to time.

as far as i see, everyone wants to create a lobby, so i will go through it in details (as much as i can)

a little not for those, who don't know anything about how dota, gc and steam exchange dota (honestly, i'm quiet puzzled too, but i think i understand the basics)
protobufs is a protocol developed by google and used by valve to exchange data before servers, clients and gc (game coordinator). protobuf messages are constructed from .proto files, and those are being constantly updated in the steam-db repo (which is a module for go-dota2)

first of all, you'd need to update protobufs and generated api code since it is, for the most part, outdated
look into go-dota2/generator/update_protos.bash, as it's responsible for the generation of protobufs. it won't work however, as these packages require a parameter "go_package" to be generated into go code. you can write a simple script to go over each .proto file and add <option go_package = "./path/to/your/go/mod/package"> at the head of each file, or go over all the protos manually :/

after you've generated the protos, go into the apigen folder and run apigen.bash (if you're on windows - well, help you god).
it will re-generate such files as client_generated.go, events_generated.go and so on to properly function with the new protobuf versions. it will spit out some errors like:
unable to find proto for: k_EMsgClientToGCOverworldDevResetPath
in this case, go to apigen/msg_overrides.go and add another message override for the problematic enum.

after you've generated the code, you'll need to update go-steam to provide it with new steam cm server list. you can either try and grab it yourself you steamre/steamkit (a few lines of c# will do the trick) or grab it from here :)
go-steam/servers.go, replace all the servers with those:
  "146.66.155.38:27017",
  "155.133.248.38:27017",
  "162.254.198.44:27017",
  "162.254.197.39:27017",
  "155.133.226.76:27017",

finally, you are ready to write your dota client.
we will go through creating a lobby.

first of all, we will need to initialize or steam client (e.g. login into our bot account)

`func main() {
    loginInfo := &steam.LogOnDetails(){
        Username: "username",
        Password: "password",
   }
}`

then, we will need to connect to the steam network and log in:
![Image](https://github.com/user-attachments/assets/ae30f5da-8f93-4de8-afec-48434f465a8a)
(don't mind the infinite time.Sleep, i just like to overthink of stuff)

so, basically, we created a loop that gets all the new events related to the steam network from the events channel, so we can handle those events as we see fit.

first, we need to handle steam.ConnectedEvent. we do that by logging in to our account and going on.

after we get steam.LoggedOnEvent (that singals that we have logged on successfully), we can proceed to working with the dota client. (don't mind the setpersonastate, just wanted to make sure it works)

in the seperate goroutine, we call createDotaLobby function after waiting for 10 seconds before steam client fully initializes (unnecessary)

![Image](https://github.com/user-attachments/assets/68573c68-4f42-41b5-b995-506748dd4878)

there is not much to explain, as we're just initializing the dota2 logger (without it, segfault will happen cause dota2 clients likes to log stuff), initializing the dota2 client itself with our steam client and our dota2 logger, inform steam network that we are now playing the game and finally, we inform the dota2 server that our connection state must be initialized now by SayHello() function.

after that, we are ready to proceed with creating the lobby object.

![Image](https://github.com/user-attachments/assets/1c442442-27f2-4d9c-99f2-6b81aed4e54a)

here, we just declare a bunch of variables and use them in CreateLobby function when creating a lobby. it's that simple.

![Image](https://github.com/user-attachments/assets/3219864b-9272-4ced-b030-7440e2abf0c7)

after that, we are ready to.. wait for another 3 seconds before steam processes our request and invite the members. if you did everything correctly, this is what you will end up with:

by the way, I made a fork of go-dota2 with updated protobufs (as of dota 7.38b).
until (and if) it will be merged into the main repo of go-dota2, feel free to use it as you see fit.
https://github.com/voltageeee/go-dota2

will be writing a documentation for this library if I will have time

![Image](https://github.com/user-attachments/assets/e5732233-ae5b-4176-9c7f-e41d122b3d4e)

**Comment by paralin** [comment]
the IP address list is now up to date, and you don't need to regen thej protos anymore (they are also up to date).

**Comment by secoldPrivate** [comment]
Any advice/note on what the actual rate limits are?
I'm in need to download a fairly large amount of replays, what is possible with a single steam account on a single IP?
How do large players like dotabuff and Stratz do it?

**Comment by paralin** [comment]
@secoldPrivate no idea! there are definitely rate limits. check [opendota](https://www.opendota.com/)

**Comment by ofcafk** [comment]
I am trying to initiate matchmaking **while already in-game**, so I cannot use dota.SetPlaying(true) because it triggers the 'app 570 already running' error. I am sending &protocol.CMsgInviteToParty directly via client.GC.Write without calling dota2.New() or SayHello(), which works fine. However, doing the same with &protocol.CMsgStartFindingMatch does not work, and dota.StartFindingMatch() is also failing. Does anyone know how to resolve this?

 `		case *steam.LoggedOnEvent:
			fmt.Printf("successfuly loged in as %s\n", details.Username)
			client.Social.SetPersonaState(steamlang.EPersonaState_Online)

			go func() {
				log.Println("sending party invite")
				var invitationUserID steamlang.SteamId = 765611987243285
				InvitePartyMember(client, invitationUserID)

				gameMode := uint32(1)
				matchType := bgcm.MatchType_MATCH_TYPE_CASUAL
				clientVersion := uint32(6763)
				matchgroups := uint32(4294967295)
				matchlanguages := uint32(4294967295)
				regionSelectFlags := uint32(0)

				dota := dota2.New(client, logrus.New())
				dota.SayHello()
				time.Sleep(4 * time.Second)
				dota.StartFindingMatch(ctx, &bgcm.CMsgStartFindingMatch{
					GameModes:         &gameMode,
					MatchType:         &matchType,
					ClientVersion:     &clientVersion,
					Matchgroups:       &matchgroups,
					Matchlanguages:    &matchlanguages,
					RegionSelectFlags: &regionSelectFlags,
				})
			}()
`

**Comment by paralin** [comment]
@ofcafk you cannot initiate matchmaking with a bot

**Comment by ofcafk** [comment]
@paralin oh... okay, thanks for answer. I almost cracked my head trying to do this

**Comment by ryodanqqe** [comment]
Getting this error

```
panic: proto: extension number 50000 is already registered on message google.protobuf.MessageOptions
        See https://protobuf.dev/reference/go/faq#namespace-conflict
        

goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.init.func1({0x103599de0?, 0x102fac200?}, {0x102fe25a0, 0x14000199c40})
        /Users/name/go/pkg/mod/google.golang.org/protobuf@v1.36.11/reflect/protoregistry/registry.go:56 +0x1e4
google.golang.org/protobuf/reflect/protoregistry.(*Types).RegisterExtension(0x14000196630, {0x102fed6e0, 0x1035a1360})
        /Users/name/go/pkg/mod/google.golang.org/protobuf@v1.36.11/reflect/protoregistry/registry.go:554 +0x4a4
github.com/golang/protobuf/proto.RegisterExtension(...)
        /Users/name/go/pkg/mod/github.com/golang/protobuf@v1.5.4/proto/registry.go:279
github.com/paralin/go-steam/protocol/protobuf.init.2()
        /Users/name/go/pkg/mod/github.com/paralin/go-steam@v0.0.0-20260416001652-4b80b1117268/protocol/protobuf/base.pb.go:591 +0xdc

```

Should I fork and fix it by myself, or it will be fixed in future?

**Comment by paralin** [comment]
@ryodanqqe I'll check on that now, thanks

**Comment by paralin** [comment]
@ryodanqqe I fixed that now, checkout master and give it a try.

**Comment by u1over** [comment]
Are there any possibilities to start a game from lobby using code? Or maybe chat command? As I can see, we can create a lobby and maybe leave it so that another member could make it playable. Any help appreciated, thanks <3

**Comment by paralin** [comment]
@u1over 1) Create lobby 2) Join spectator slot 3) Wait for players to join, at least 1 per each team 4) Send LaunchPracticeLobby

**Comment by AngelloFD** [comment]
Hey everyone, just a question so this issue can be resolved accordingly. Will the docs be shown/asked via the DeepWiki tag in the readme?
